export const GET_DISH_SUCCESS = "GET_DISH_SUCCESS";
export const GET_DISH_FAILURE = "GET_DISH_FAILURE";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCCESS";
export const UPDATE_DISH_FAILURE = "UPDATE_DISH_FAILURE";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_FAILURE = "DELETE_DISH_FAILURE";
