export const GET_CUSTOMER_DELIVERY_ADDRESS_SUCCESS =
  "GET_CUSTOMER_DELIVERY_ADDRESS_SUCCESS";
export const GET_CUSTOMER_DELIVERY_ADDRESS_FAILURE =
  "GET_CUSTOMER_DELIVERY_ADDRESS_FAILURE";
export const ADD_CUSTOMER_DELIVERY_ADDRESS_SUCCESS =
  "ADD_CUSTOMER_DELIVERY_ADDRESS_SUCCESS";
export const ADD_CUSTOMER_DELIVERY_ADDRESS_FAILURE =
  "ADD_CUSTOMER_DELIVERY_ADDRESS_FAILURE";
