export const CUSTOMER_SIGNUP_SUCCESS = "CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGNUP_FAILURE = "CUSTOMER_SIGNUP_FAILURE";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAILURE = "CUSTOMER_UPDATE_FAILURE";
export const CUSTOMER_GET_DATA_SUCCESS = "CUSTOMER_GET_DATA_SUCCESS";
export const CUSTOMER_GET_DATA_FAILURE = "CUSTOMER_GET_DATA_FAILURE";
