export const ON_LIKE_CLICK_SUCCESS = "ON_LIKE_CLICK_SUCCESS";
export const ON_LIKE_CLICK_FAILURE = "ON_LIKE_CLICK_FAILURE";
export const GET_CUSTOMER_LIKES_SUCCESS = "GET_CUSTOMER_LIKES_SUCCESS";
export const GET_CUSTOMER_LIKES_FAILURE = "GET_CUSTOMER_LIKES_FAILURE";
