export const RESTAURANT_SIGNUP_SUCCESS = "RESTAURANT_SIGNUP_SUCCESS";
export const RESTAURANT_SIGNUP_FAILURE = "RESTAURANT_SIGNUP_FAILURE";
export const RESTAURANT_UPDATE_SUCCESS = "RESTAURANT_UPDATE_SUCCESS";
export const RESTAURANT_UPDATE_FAILURE = "RESTAURANT_UPDATE_FAILURE";
export const RESTAURANT_GET_DATA_SUCCESS = "RESTAURANT_GET_DATA_SUCCESS";
export const RESTAURANT_GET_DATA_FAILURE = "RESTAURANT_GET_DATA_FAILURE";
