export const ADD_REMOVE_DISHES_FROM_CART = "ADD_REMOVE_DISHES_FROM_CART";
export const UPDATE_LIST_OF_RESTAURANTS_ORDERING_FROM =
  "UPDATE_LIST_OF_RESTAURANTS_ORDERING_FROM";
export const UPDATE_NUMBER_OF_ITEMS_IN_CART = "UPDATE_NUMBER_OF_ITEMS_IN_CART";
