export const ADD_REMOVE_DISHES_FROM_CART = "ADD_REMOVE_DISHES_FROM_CART";
export const UPDATE_RESTAURANT_ORDERING_FROM =
  "UPDATE_RESTAURANT_ORDERING_FROM";
export const UPDATE_NUMBER_OF_ITEMS_IN_CART = "UPDATE_NUMBER_OF_ITEMS_IN_CART";
export const RESTAURANT_CHANGE_ALERT = "RESTAURANT_CHANGE_ALERT";
export const CHANGE_ORDER_RESTAURANT = "CHANGE_ORDER_RESTAURANT";
export const RESET_ORDER_RESTAURANT = "RESET_ORDER_RESTAURANT";
export const SET_ORDER_MODE = "SET_ORDER_MODE";
